name: Build and Push to GHCR

on:
  workflow_dispatch:
  #push:
  #  branches:
  #    - master
  #schedule:
  #  - cron: "0 0 * * *"
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get latest commit SHA
        id: git
        run: echo "LLAMA_COMMIT=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      #- name: Login to GitHub Container Registry
      #  uses: docker/login-action@v2
      #  with:
      #    registry: ghcr.io
      #    username: ${{ secrets.GHCR_USERNAME }}
      #    password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push image to GHCR
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/arm64
          push: false
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ env.LLAMA_COMMIT }}
          build-args: |
            LLAMA_COMMIT=${{ env.LLAMA_COMMIT }}
            BUILDPLATFORM_builder=linux/amd64
            BUILDPLATFORM_runner=linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
